name: CI Pipeline

on: [push, pull_request]

defaults:
  run:
    working-directory: ./src

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run check
        run: composer check

      - name: Run PHPStan
        run: composer phpstan

      - name: Run PHPMD
        run: composer phpmd

      - name: Run Tests
        run: composer test
